const byId=id=>document.getElementById(id);
const token=document.querySelector('meta[name="task-token"]').content;
let choices=[],busy=false,timer;
function notice(text,error=false){byId('notice').textContent=text;byId('notice').className=error?'notice error':'notice';}
async function api(path,data){const response=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Task-Token':token,...(data===undefined?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw Error(value.error||'读取失败，请重试');return value;}
function options(id,items){const element=byId(id);element.replaceChildren();for(const [value,label] of items){const option=document.createElement('option');option.value=value;option.textContent=label;element.append(option);}element.disabled=!items.length;}
function selected(){return choices.find(x=>String(x.entry)===byId('source').value);}
function chooseSource(){const choice=selected();if(!choice)return;options('records',choice.arrays.map(x=>[x.pointer,`${x.pointer||'全部记录'} · ${x.count} 条`]));byId('records').value=choice.records_pointer;options('total',[['','不提供总量'],...choice.totals.map(x=>[x.pointer,`${x.pointer} · ${x.value} 条`])]);if(choice.totals.length)byId('total').value=choice.totals[0].pointer;options('page',[['','不翻页'],...choice.query_fields.map(x=>[x,x])]);byId('page').value=choice.query_fields.find(x=>/^(page|page_no|pageNum|pageNumber|p)$/i.test(x))||'';options('identity',[['','按整条记录去重'],...choice.fields.map(x=>[x,x])]);byId('identity').value=choice.fields.find(x=>/^(id|编号|uuid)$/i.test(x))||'';byId('sourceInfo').textContent=choice.url;hint();updateButtons();}
function hint(){const choice=selected();if(!choice)return;const fields=choice.query_fields.filter(x=>x!==byId('page').value);byId('queryHint').textContent='可填写的列名：'+(fields.join('、')||'没有可变化的查询条件');}
function updateButtons(){byId('run').disabled=busy||!choices.length||!byId('query').value.trim();byId('demo').disabled=busy;byId('har').disabled=busy;byId('stop').disabled=!busy;}
function loadChoices(value){choices=value.choices;options('source',choices.map(x=>[String(x.entry),`来源 ${x.entry} · ${new URL(x.url).hostname} · ${x.captured_count} 条`]));chooseSource();}
function render(value){busy=value.status==='运行中';byId('badge').textContent=value.status;byId('badge').className='badge'+(value.status==='完成'?' done':value.status==='未完成'?' failed':'');byId('recordCount').textContent=(value.records||0).toLocaleString('zh-CN');byId('taskCount').textContent=`${value.completed_tasks||0} / ${value.tasks||0}`;byId('pageCount').textContent=value.pages||value.page||0;byId('resume').disabled=busy||value.status!=='未完成';byId('download').disabled=busy||!value.export_checked;byId('resultText').textContent=value.error||(busy?`正在读取第 ${value.task||1} 项查询，请保持本机程序运行。`:value.status==='完成'?`导出记录数已核对${value.total_checked?'，来源总量一致':''}。结果保存在本机，可下载查看。`:'完成后可下载表格、逐条记录与中文结论。');updateButtons();}
async function poll(){clearTimeout(timer);try{const value=await api('/api/status');render(value);if(busy)timer=setTimeout(poll,700);}catch(error){notice(error.message,true);busy=false;updateButtons();}}
byId('demo').onclick=async()=>{try{notice('正在载入本机模拟查询…');const value=await api('/api/demo',{});loadChoices(value);byId('query').value=value.csv;updateButtons();notice('已载入 12 项模拟查询，每项 37 条。点击开始批量查询。');}catch(error){notice(error.message,true);}};
byId('har').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>32*1024*1024)throw Error('浏览记录超过 32 MiB，请只导出相关查询');notice('正在读取浏览记录…');loadChoices(await api('/api/import',{har:await file.text()}));notice(`已找到 ${choices.length} 个可用读取来源，请选择并填写查询清单。`);}catch(error){notice(error.message,true);}};
byId('jobs').onchange=async event=>{const file=event.target.files[0];if(file){if(file.size>4*1024*1024){notice('参数表过大，请拆分查询清单。',true);return;}byId('query').value=await file.text();notice('查询清单已导入。');updateButtons();}};
byId('source').onchange=chooseSource;byId('page').onchange=hint;byId('query').oninput=updateButtons;
byId('run').onclick=async()=>{try{const value=await api('/api/run',{entry:Number(byId('source').value),csv:byId('query').value,records_pointer:byId('records').value,total_pointer:byId('total').value,page_param:byId('page').value,id_field:byId('identity').value,max_pages:Number(byId('maxPages').value),interval:Number(byId('interval').value)});render(value);notice('批量查询已开始。');poll();}catch(error){notice(error.message,true);}};
byId('resume').onclick=async()=>{try{render(await api('/api/run',{resume:true,max_pages:Number(byId('maxPages').value),interval:Number(byId('interval').value)}));notice('正在续跑上次任务，已完成页面会保留。');poll();}catch(error){notice(error.message,true);}};
byId('stop').onclick=async()=>{try{await api('/api/stop',{});notice('正在停止，已完成页面会保留。');}catch(error){notice(error.message,true);}};
byId('download').onclick=async()=>{try{const response=await fetch('/api/export',{headers:{'X-Task-Token':token}});if(!response.ok)throw Error((await response.json()).error);const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='网页查询结果.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('结果包已下载。');}catch(error){notice(error.message,true);}};
poll();
